# **Pandas**

### **Series**

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {"0": "A", "1": "B", "2": "C", "3": "D", "4": "E"}

pd.Series(data)

0    A
1    B
2    C
3    D
4    E
dtype: object

### **DataFrame**

In [4]:
df = pd.DataFrame(
    data=np.random.randn(5, 3),
    index=["A", "B", "C", "D", "E"],
    columns=["X", "Y", "Z"],
)
df

          X         Y         Z
A  0.012896  0.195366  0.826495
B  0.425594 -0.662361 -1.594494
C  0.289355  0.769336  0.093452
D -0.423952 -0.329652  0.627252
E -0.048211  0.372945 -0.521999

In [5]:
sub_df = df[["X"]]
sub_df

          X
A  0.012896
B  0.425594
C  0.289355
D -0.423952
E -0.048211